kind: pipeline
steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn test
  - name: Sonarqube
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=BOOTstrap2021 -Dsonar.host.url=https://fast-falcon-40.loca.lt
  - name: Quality gate
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=BOOTstrap2021 -Dsonar.host.url=https://fast-falcon-40.loca.lt
  - name: Build WAR
    image: maven:3-jdk-11
    commands:
      - mvn package
  - name: Server-master
    image: alpine
    commands:
      - cd target/
      - apk add curl
      - stat ventas-0.0.1-SNAPSHOT.war
      - mv  ventas-0.0.1-SNAPSHOT.war rps.war
      - curl -v -u admin:admin -T rps.war 'http://ad3e-2800-98-1112-b1b-dd56-4d93-76bf-a41f.ngrok.io/manager/text/deploy?path=/rps&update=true'
  
