kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn test
  - name: Sonarqube
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=BOOTstrap2021 -Dsonar.host.url=https://itchy-robin-12.loca.lt
  - name: Quality gate
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=BOOTstrap2021 -Dsonar.host.url=https://itchy-robin-12.loca.lt
  - name: Build WAR
    image: maven:3-jdk-11
    commands:
      - mvn package
  - name: Server-uat
    image: alpine
    commands:
     - cd target/
     - apk add curl
     - stat ventas-0.0.1-SNAPSHOT.war
     - mv  ventas-0.0.1-SNAPSHOT.war uat.war
     - curl -v -u admin:admin -T uat.war 'https://c334-2800-98-1127-1117-18ce-f265-8fc8-f399.ngrok.io/manager/text/deploy?path=/uat&update=true'
    when:
     branch:
       - uat
  - name: Server-Dev
    image: alpine
    commands:
     - cd target/
     - apk add curl
     - stat ventas-0.0.1-SNAPSHOT.war
     - mv  ventas-0.0.1-SNAPSHOT.war dev.war
     - curl -v -u admin:admin -T dev.war 'https://c334-2800-98-1127-1117-18ce-f265-8fc8-f399.ngrok.io/manager/text/deploy?path=/dev&update=true'
    when:
     branch:
       - dev
  - name: Server-Master
    image: alpine
    commands:
     - cd target/
     - apk add curl
     - stat ventas-0.0.1-SNAPSHOT.war
     - mv  ventas-0.0.1-SNAPSHOT.war rps.war
     - curl -v -u admin:admin -T rps.war 'https://c334-2800-98-1127-1117-18ce-f265-8fc8-f399.ngrok.io/manager/text/deploy?path=/rps&update=true'
    when:
     branch:
       - master   
  - name: Correo
    image: drillster/drone-email
    settings:
      subject: pipeline
      from: castaneda161618@unis.edu.gt
      host: smtp.gmail.com
      port: 465
      username:
        from_secret: Usuario
      password: 
        from_secret: Password

      recipients:
          - castaneda161618@unis.edu.gt
          - jflores@unis.edu.gt
    when:
      status:
      - success
      - failure 
  - name: Slack
    image: plugins/slack
    settings:
      webhook: 
        from_secret: Siuuu
      channel: general
    when:
      status:   
      - success
      - failure 
