kind: pipeline
steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn test
  - name: Sonarqube
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=BOOTstrap2021 -Dsonar.host.url=https://tender-falcon-91.loca.lt
  - name: Quality gate
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=BOOTstrap2021 -Dsonar.host.url=https://tender-falcon-91.loca.lt
  - name: Build WAR
    image: maven:3-jdk-11
    commands:
      - mvn package
  - name: Server-master
    image: alpine
    commands:
      - cd target/
      - apk add curl
      - stat ventas-0.0.1-SNAPSHOT.war
      - mv  ventas-0.0.1-SNAPSHOT.war rps.war
      - curl -v -u admin:admin -T rps.war 'http://7bda-2800-98-1112-b1b-41e7-c9ce-d2e-d4c8.ngrok.io/manager/text/deploy?path=/rps&update=true'
  - name: Correo
    image: drillster/drone-email
    settings:
      from: castaneda161618@unis.edu.gt
      host: smtp.gmail.com
      port: 465
      username:
        from_secret: Usuario
      password: 
        from_secret: Password

      recipients:
          - [castaneda161618@unis.edu.gt, jflores@unis.edu.gt]
    when:
      status:
      - success
      - failure
  
