kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn test
  - name: Correo
    image: drillster/drone-email
    settings:
      subject: pipeline
      from: castaneda161618@unis.edu.gt
      host: smtp.gmail.com
      port: 465
      username:
        from_secret: Usuario
      password: 
        from_secret: Password

      recipients:
          - castaneda161618@unis.edu.gt
          - jflores@unis.edu.gt
    when:
      status:
      - success
      - failure 
  - name: Slack
    image: plugins/slack
    settings:
      webhook: webhook
      channel: general
    when:
      status:   
      - success
      - failure 
