kind: pipeline
steps:
  - name: Build WAR
    image: maven:3-jdk-11
    commands:
      - mvn package
  - name: Server Deploy
    image: maven:3-jdk-11
    commands:
      - mvn clean tomcat:deploy
  
